apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-loan
  labels:
    app: backend-loan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-loan
  template:
    metadata:
      labels:
        app: backend-loan
    spec:
      containers:
      - name: backend-loan
        image: backend-loan:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysql-db"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "admin123"
        - name: MYSQL_DATABASE
          value: "bluevault_db"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-loan
spec:
  type: ClusterIP
  selector:
    app: backend-loan
  ports:
  - port: 5000
    targetPort: 5000