server {
    listen 80 default_server;
    server_name _;

    resolver 172.20.0.10 valid=5s;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
    }

    # Route for EMI Backend
    location /api/calculate {
        set $target_emi "backend-emi.default.svc.cluster.local:5000";
        proxy_pass http://$target_emi/api/calculate;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route for Loan Backend
    location /api/submit-loan {
        set $target_loan "backend-loan.default.svc.cluster.local:5000";
        proxy_pass http://$target_loan/submit-loan;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route for SIP Backend
    location /sip-calc/api/calculate {
        set $target_sip "backend-sip.default.svc.cluster.local:5000";
        proxy_pass http://$target_sip/calculate;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /sip-calc/api/ {
        set $target_sip_base "backend-sip.default.svc.cluster.local:5000";
        proxy_pass http://$target_sip_base/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
