server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
    }

    # Route for EMI Backend
    location /api/calculate {
        proxy_pass http://backend-emi:5000/api/calculate;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route for Loan Backend
    location /api/submit-loan {
        proxy_pass http://backend-loan:5000/submit-loan;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route for SIP Backend
    location /sip-calc/api/ {
        proxy_pass http://backend-sip:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
