name: Tamwil Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build Docker Images, Deploy to EKS & Publish GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy Frontend to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Frontend

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push Docker Images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build & Push EMI Backend
        docker build -t $ECR_REGISTRY/tamwil-backend-emi:$IMAGE_TAG -t $ECR_REGISTRY/tamwil-backend-emi:latest ./backend-emi
        docker push $ECR_REGISTRY/tamwil-backend-emi --all-tags

        # Build & Push SIP Backend
        docker build -t $ECR_REGISTRY/tamwil-backend-sip:$IMAGE_TAG -t $ECR_REGISTRY/tamwil-backend-sip:latest ./backend-sip
        docker push $ECR_REGISTRY/tamwil-backend-sip --all-tags

        # Build & Push Loan Backend
        docker build -t $ECR_REGISTRY/tamwil-backend-loan:$IMAGE_TAG -t $ECR_REGISTRY/tamwil-backend-loan:latest ./backend-loan
        docker push $ECR_REGISTRY/tamwil-backend-loan --all-tags

        # Build & Push Frontend Proxy
        docker build -t $ECR_REGISTRY/tamwil-frontend-proxy:$IMAGE_TAG -t $ECR_REGISTRY/tamwil-frontend-proxy:latest -f Dockerfile .
        docker push $ECR_REGISTRY/tamwil-frontend-proxy --all-tags

    - name: Update Kubeconfig & Deploy to EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name finance-homepage-cluster
        
        sed -i "s|image: .*tamwil-backend-emi.*|image: ${{ steps.login-ecr.outputs.registry }}/tamwil-backend-emi:${{ github.sha }}|g" k8s/backend_emi.yaml
        sed -i "s|image: .*tamwil-backend-sip.*|image: ${{ steps.login-ecr.outputs.registry }}/tamwil-backend-sip:${{ github.sha }}|g" k8s/backend_sip.yaml
        sed -i "s|image: .*tamwil-backend-loan.*|image: ${{ steps.login-ecr.outputs.registry }}/tamwil-backend-loan:${{ github.sha }}|g" k8s/backend_loan.yaml
        sed -i "s|image: .*tamwil-frontend-proxy.*|image: ${{ steps.login-ecr.outputs.registry }}/tamwil-frontend-proxy:${{ github.sha }}|g" k8s/frontend-proxy.yaml

        kubectl apply -f k8s/
